svg = [
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_WIDTH}" height="{SVG_HEIGHT}" viewBox="0 0 {SVG_WIDTH} {SVG_HEIGHT}">',
    '  <rect width="100%" height="100%" rx="18" fill="#0d1117" stroke="#30363d" stroke-width="1.5"/>',
    '  <style>',
    f'    .mono {{ font-family: ui-monospace, "SF Mono", "Fira Code", "JetBrains Mono", Consolas, monospace; font-size: {FONT_SIZE}px; }}',
    '    .title { fill: #58a6ff; font-weight: bold; }',
    '    .sec { fill: #d2a8ff; font-weight: bold; }',
    '    .label { fill: #ff9b54; }',
    '    .val { fill: #8cb4d9; }',
    '    .dim { fill: #484f58; }',
    '    .row { opacity: 0; animation: fadeSlide 0.2s ease-out forwards; }',
    '    @keyframes fadeSlide {',
    '      from { opacity: 0; transform: translateY(4px); }',
    '      to { opacity: 1; transform: translateY(0); }',
    '    }',
    '  </style>',
    '',
    '  <!-- Left Column: Embedded Image (Scaled Even Smaller) -->',
    # --- CHANGE: Apply smaller scale transform here ---
    f'  <g transform="translate({PAD_X}, {PAD_Y}) scale({IMG_SCALE})">',
    f'    {raw_svg_body}',
    '  </g>',
    '',
    '  <!-- Right Column: Larger, Positioned Profile Info -->',
]